# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.
#
# Learn more about config at: https://juju.is/docs/sdk/config

options:
  scrape_interval:
    description: Frequency at which metrics are scraped.
    type: string
  scrape_timeout:
    description: Timeout interval when scraping a job.
    type: string
  proxy_url:
    description: Proxy URL for accessing metrics endpoints.
    type: string
  relabel_configs:
    description: YAML string formatted scrape target relabeling configuration.
    type: string
  metrics_relabel_configs:
    description: YAML string formatted metrics relabeling configuration.
    type: string
  sample_limit:
    description: Maximum number of samples per scrape (0=unlimited)
    type: int
  label_limit:
    description: Maximum number of labels per scrape (0=unlimited)
    type: int
  label_name_length_limit:
    description: Maximum length of label name (0=unlimited)
    type: int
  label_value_length_limit:
    description: Maximum lenght of label value (0=unlimited)
    type: int
